#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs udev /dev
mount -t tmpfs tmpfs /run
mount -t tmpfs tmpfs /tmp

/sbin/mdev -s
mount -t msdos -o rw,sync,nodev,nosuid /dev/mmcblk0p1 /mnt
/usr/bin/dumper&
